### PR TITLE
Update LICENSE.md with MINPACK copyright

### PR DESCRIPTION
**Pull request by anriseth**
Addressing https://github.com/anriseth/LineSearches.jl/commit/582b61276bf0ed978809bba97a0d77e858fe5ed4#commitcomment-19450850

I have added the MINPACK license here @tkelman. I'm not so familiar with licensing issues, is this the correct way to do it?

### CODE REVIEW

**Comment by tkelman** [comment]
This seems fine to me. Weren't there several pieces of translated code here?

**Comment by anriseth** [comment]
There were four algorithms taken from Optim. 
- `morethuente!` now has licensing fixed
- `backtracking!` This code is just following the exact steps of a basic algorithm available in the mathematics literature (no code translation)
- `strongwolfe!` same as `backtracking!`
- `hagerzhang!`: I don't know how this came about. I assume whoever wrote it (johnmyleswhite ?) was just following the algorithm as described in the paper by Hager and Zhang (reference below)


*W. W. Hager and H. Zhang, Algorithm 851: CG_DESCENT, A conjugate gradient method with guaranteed descent, ACM Transactions on Mathematical Software, 32 (2006), 113-137*

**Comment by tkelman** [comment]
Ahk, if this is the only place that came from minpack then I think you're good. I may have gotten confused looking at diffs where this lived in several different files over time.

Has the code that lives here been deleted from Optim by now, or is it still partially duplicated?

**Comment by anriseth** [comment]
Yes, the MINPACK code was originally in two files, mt_cstep.jl and mt_linesearch.jl. I have movet the contents of mt_cstep.jl into mt_linesearch.jl, and then renamed the file to morethuente.jl.

When this is merged, I'll tag a patch and send a PR to METADATA.

The LineSearches code is still duplicated in Optim, but will be removed when JuliaOpt/Optim.jl#277 is merged.

**Comment by tkelman** [comment]
Do you want to do this as 0.1.1, or replace the 0.1.0 tag since it hasn't been published yet?

**Comment by anriseth** [comment]
I'll try to replace the 0.1.0 tag and update the existing PR on METADATA
(fingers crossed I don't mess it up)

**Pull request merged**
